-- # Create Table # --
-- [CREATE] APP_INFO Table 

CREATE TABLE PROJECT_INFO(
PROJECT_NAME		VARCHAR(1000)	NOT NULL,
OS 					VARCHAR(1000)	NOT NULL,
APP_PACKAGE 		VARCHAR(1000)	NOT NULL,
APP_ACTIVITY		VARCHAR(1000)	NOT NULL,
APP_PATH 			VARCHAR(1000),
KR_TECH_WRITING 	VARCHAR(1000),
EN_TECH_WRITING 	VARCHAR(1000),
JP_TECH_WRITING 	VARCHAR(1000)
);

CREATE TABLE DETAIL_TEST_INFO(
UDID				VARCHAR(1000)	NOT NULL,
STEP_NO 				INT,
TC_BEHAVIOR_METHOD 	VARCHAR(1000) character set utf8,
TC_BEHAVIOR_ELEMENT	VARCHAR(1000) character set utf8,
TC_EXPECTED_METHOD	VARCHAR(1000) character set utf8,
TC_EXPECTED_ELEMENT	VARCHAR(1000) character set utf8,
TC_EXPECTED_OUTPUT 	VARCHAR(1000) character set utf8,
TC_INPUT		 	VARCHAR(1000) character set utf8,
TC_SCROLL_VALUE	 	VARCHAR(1000) character set utf8,
TC_SLEEP_TIME		INT,
RESULTS			 	VARCHAR(1000) character set utf8,
STACK_TRACE		 	VARCHAR(8000) character set utf8,
ELE_IMG			 	VARCHAR(1000) character set utf8,
FULL_IMG		 	VARCHAR(1000) character set utf8,
DATE				TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TEST_MERGE_IMG(
UDID			VARCHAR(1000)	character set utf8,
TEST_NAME		VARCHAR(1000)	character set utf8,
MERGE_IMG_NAME	VARCHAR(1000)	character set utf8,
DATE				TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TEST_LOG(
UDID 			VARCHAR(1000)	character set utf8
);

-- 테이블 비우기
TRUNCATE TABLE TEST_LOG;

-- 중복 제거
SELECT DISTINCT UDID FROM dev_mit.DETAIL_TEST_INFO;

-- # Insert Table # --
-- [INSERT] APP_INFO Table
INSERT INTO PROJECT_INFO
VALUES('SODA', 'ANDROID', 'com.ahnlab.v3mobilesecurity.soda', 'com.ahnlab.v3mobilesecurity.main.DummyMain', null, 'VMS_Android30_Korea_ko_kr.xml', null, null);


# Select Table
Select col.name from table.name where condition;

# Drop Table 
DROP TABLE PROJECT_INFO;

# Update Table 
UPDATE PROJECT_INFO SET APP_PATH='/mblia/Resource/App/SODA/VMS_SODA.apk' WHERE PROJECT_NAME='SODA';


# Data 조회 쿼리
SELECT A.UDID, A.STEP_NO , A.TC_BEHAVIOR_METHOD , A.TC_BEHAVIOR_ELEMENT, A.TC_EXPECTED_METHOD, A.TC_EXPECTED_ELEMENT, A.TC_EXPECTED_OUTPUT , A.TC_INPUT, A.TC_SCROLL_VALUE, A.TC_SLEEP_TIME, A.RESULTS, A.STACK_TRACE, A.ELE_IMG, A.FULL_IMG, C.MERGE_IMG_NAME, A.DATE FROM dev_mit.DETAIL_TEST_INFO A, dev_mit.TEST_LOG B, dev_mit.TEST_MERGE_IMG C where A.UDID = B.UDID AND A.UDID = C.UDID order by A.DATE ASC;